# -*- coding: utf-8 -*-
"""apple_stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xcBnVOJkr4MmF5WRqtsWg9dvgprNtOO
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

# Download Apple stock data from Yahoo Finance for 2024
data = yf.download("AAPL", start="2024-01-01", end="2024-12-31")

# Calculate moving averages (20-day and 50-day)
data['MA20'] = data['Close'].rolling(window=20).mean()
data['MA50'] = data['Close'].rolling(window=50).mean()

# Plot the stock price and moving averages
plt.figure(figsize=(10,5))
plt.plot(data['Close'], label="AAPL Close")
plt.plot(data['MA20'], label="MA20")
plt.plot(data['MA50'], label="MA50")
plt.legend()
plt.title("Apple Stock Price with 20 & 50 Day Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price (USD)")
plt.show()